### ISSUE TITLE
hi, can you tell me, what is the reset command, use in IIC.

### ISSUE THREAD

**Issue by powermcu** [ghent360/RTD-2660-Programmer#1]
hi, can you tell me, what is the reset command, use in IIC.

**Comment by ghent360** [comment]
I'm not sure I understand the question, can you elaborate?

**Comment by powermcu** [comment]
for example:

this is Erase command
  SPICommonCommand(E_CC_WRITE_AFTER_EWSR, 1, 0, 1, 0); // Unprotect the
Status Register
SPICommonCommand(E_CC_WRITE_AFTER_WREN, 1, 0, 1, 0); // Unprotect the flash
SPICommonCommand(E_CC_ERASE, 0xc7, 0, 0, 0); // Chip Erase

what is the reset command ?

---

marsboard

_From:_ ghent360 notifications@github.com
_Date:_ 2016-01-12 09:37
_To:_ ghent360/RTD-2660-Programmer RTD-2660-Programmer@noreply.github.com
_CC:_ powermcu marsboard@gmail.com
_Subject:_ Re: [RTD-2660-Programmer] hi, can you tell me, what is the reset
command, use in IIC. (#1)
I'm not sure I understand the question, can you elaborate?

**Comment by ghent360** [comment]
The example you gave is a command sequence to erase the SPI flash. When you
ask for a reset command, what is it you want to reset?

**Comment by powermcu** [comment]
i Successfully upgraded the firmware, then i want to reset the chip, Now I'm all manually reset.

marsboard
 From: ghent360Date: 2016-01-12 16:40To: ghent360/RTD-2660-ProgrammerCC: powermcuSubject: Re: [RTD-2660-Programmer] hi, can you tell me, what is the reset command, use in IIC. (#1)The example you gave is a command sequence to erase the SPI flash. When you

ask for a reset command, what is it you want to reset?

**Comment by ghent360** [comment]
I don't think it is possible to reset the chip completely via IIC.
