### ISSUE TITLE
i am not getting port in arduino but it installed correctly

### ISSUE THREAD

**Issue by akashpatel123** [ghent360/RTD-2660-Programmer#10]
![untitled](https://user-images.githubusercontent.com/35725052/35268070-28d6ed80-004e-11e8-95e0-705a6eeaaad6.jpg)

**Comment by akashpatel123** [comment]
![untitled](https://user-images.githubusercontent.com/35725052/35268349-db91939e-004e-11e8-8569-b2ece4798d0d.png)




just see the bottom right corner

**Comment by ghent360** [comment]
Not sure how this question relates to my project.
