### ISSUE TITLE
FT232H support

### ISSUE THREAD

**Issue by 424778940z** [ghent360/RTD-2660-Programmer#5]
need FT232H suppor...

**Comment by ghent360** [comment]
Check https://github.com/juancgarcia/RTD-2660-Programmer-Python

**Comment by ghent360** [comment]
There is also this port: https://github.com/adafruit/Adafruit_RTD266X_I2CFlasher

**Comment by 424778940z** [comment]
got it, thanks

**Comment by bhura112** [comment]
hello guysz i need your support,i am using RTD2660 with FT232H ,its not working , when i reset/erase or program the RTD2660 its send me back a response on rova tool ack not recevied
