### ISSUE TITLE
Python port, and native linux port for Raspberry Pi

### ISSUE THREAD

**Issue by klirichek** [ghent360/RTD-2660-Programmer#9]
Hello.

I've adapted your code to work with native i2c port on raspberry pi. Added cmake proj for native build for it.

Also when playing with code I've prototyped the whole of it on python and found that version more 'hacker-friendly' (since it is not necessary to have a compiler when you want to make a change).

Feel free to copy anything like ideas, snippets, etc.
(I an in 'fork' section, seems to be the only one).

**Comment by ghent360** [comment]
Thank you for the email.

Sadly you are not the first to attempt such endeavor. I edited the readme
file with links to know ports of this code. Hopefully it would help.

~Venelin
